### ISSUE TITLE
Could we have a version not using Ansible?

### ISSUE THREAD

**Issue by yubrshen** [alexander-yakushev/clj-vagrant-template#1]
As I'm using Windows which does not have good support to Ansible. I tried to make it working, but it took a lots of time defeating the whole purpose of time saving. 

I feel that it might be better to have a version not using Ansible, instead just use shell script to do the provisioning, less dependency, and wider adoption.

I'm trying to adapting your template with that of another project:
https://github.com/pattinsont/Ukelele

I've get to the point of having Java and lein working. But I haven't figured out how to get nrepl working. If you have any Unix command line example of setting up nrepl it would be greatly appreciated.

**Comment by alexander-yakushev** [comment]
I don't anymore feel that Vagrant is the correct way to solve this problem. I mostly use Docker now, however not for Clojure-based projects. I recommend looking in that direction.

**Comment by yubrshen** [comment]
OK. I'll consider Docker.

Thanks for replying.
